#!/usr/bin/env python3

import os, argparse, json

from neubua.metrics import *
from neubua.io import loadswc, saveswc
from collections import deque
import numpy as np
from scipy.spatial.distance import cdist

parser = argparse.ArgumentParser(
    description='Arguments for comparing two swc files.')
parser.add_argument(
    '--target',
    type=str,
    default=None,
    required=True,
    help='The input target swc file.')
parser.add_argument(
    '--groundtruth',
    type=str,
    default=None,
    required=True,
    help='The input ground truth swc file.')
parser.add_argument(
    '--sigma',
    type=float,
    default=3.,
    required=False,
    help='The sigma value to use for the Gaussian function in NetMets.')
args = parser.parse_args()

# If ground truth is present, use the ground truth to evaluate the reconstruction
# The results will be written to the front of the swc file
swc1 = loadswc(args.target)  # Load the ground truth
swc2 = loadswc(args.groundtruth)  # Load the ground truth
swc2[:, 5] = 1

d = cdist(swc1[:, 2:5], swc2[:, 2:5])

print("%s, %s" % (np.mean(d.min(axis=1)), np.std(d.min(axis=1))))
